# Generated by Django 6.0.1 on 2026-01-27 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id_kategori', models.AutoField(primary_key=True, serialize=False)),
                ('nama_kategori', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Kategori',
                'db_table': 'kategori',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id_status', models.AutoField(primary_key=True, serialize=False)),
                ('nama_status', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Status',
                'db_table': 'status',
            },
        ),
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id_produk', models.AutoField(primary_key=True, serialize=False)),
                ('nama_produk', models.CharField(max_length=200)),
                ('harga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kategori_id', models.ForeignKey(db_column='kategori_id', on_delete=django.db.models.deletion.CASCADE, related_name='produk', to='produk.kategori')),
                ('status_id', models.ForeignKey(db_column='status_id', on_delete=django.db.models.deletion.CASCADE, related_name='produk', to='produk.status')),
            ],
            options={
                'verbose_name_plural': 'Produk',
                'db_table': 'produk',
            },
        ),
    ]
