# Generated by Django 6.0.1 on 2026-01-27 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kategori',
            name='nama_kategori',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
